name: "Pull Request"
description: "Propose changes to the extension or cheatsheets"
title: "<type>: <short description>"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your contribution! Please provide a concise summary below.

  - type: textarea
    id: summary
    attributes:
      label: What changed
      description: Briefly describe what this PR changes and why.
    validations:
      required: true

  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      options:
        - label: Extension code (TypeScript / UI)
        - label: Default cheatsheets under assets/cheatsheets/
        - label: Icons under assets/
        - label: Documentation (README, templates)

  - type: textarea
    id: details
    attributes:
      label: Details
      description: List each file or cheatsheet touched and the reason.
      placeholder: |
        - assets/cheatsheets/docker.md – added compose examples
        - src/default-tags.ts – mapped docker → docker.svg
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (if UI changes)
      description: Drag-and-drop images.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I ran npm run lint locally and fixed warnings
          required: true
        - label: I updated src/default-tags.ts if I introduced new tags/topics
          required: false
        - label: I added/updated icons in assets/ if needed and ran npm run normalize:icons
          required: false

