name: "Cheatsheet Request / Update"
description: "Request a new default cheatsheet or propose an update to an existing one"
title: "cheatsheet: <language/tool> – <add/update>"
labels:
  - enhancement
  - cheatsheets
body:
  - type: markdown
    attributes:
      value: |
        Help expand or improve the built-in cheatsheets. Provide sources if possible.

  - type: dropdown
    id: type
    attributes:
      label: Request type
      options:
        - Add new cheatsheet
        - Update existing cheatsheet
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Cheatsheet name
      placeholder: e.g. Kubernetes, Zig, Raycast API, Python
    validations:
      required: true

  - type: input
    id: slug
    attributes:
      label: Suggested filename (slug)
      description: Lowercase and hyphenated, will live under assets/cheatsheets/
      placeholder: e.g. kubernetes.md
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary of content
      description: A short outline or bullets of sections to include.
      placeholder: |
        - CLI basics
        - Pods / Deployments
        - Services / Ingress
        - Helm commands
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References / sources
      description: Official docs, trusted guides, or your own notes.
      placeholder: URLs or notes
    validations:
      required: false

  - type: textarea
    id: tags
    attributes:
      label: Suggested tags
      description: Tags help discovery; these may inform icon mapping in src/default-tags.ts.
      placeholder: e.g. kubernetes, k8s, containers
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Are you planning to open a PR with the markdown?
      options:
        - label: Yes, I will open a PR with the cheatsheet markdown
        - label: No, please consider this a request for maintainers/community

