name: Sync Cheatsheets from DevHints

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1" # weekly on Mondays at 07:00 UTC

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone upstream cheatsheets
        run: |
          rm -rf external-cheatsheets
          git clone --depth 1 https://github.com/rstacruz/cheatsheets.git external-cheatsheets

      - name: Prepare destination
        run: |
          mkdir -p assets/cheatsheets
          # Remove existing synced .md files before copying
          find assets/cheatsheets -maxdepth 1 -type f -name '*.md' -delete

      - name: Copy filtered .md files (exclude directories and disallowed files)
        shell: bash
        run: |
          set -euo pipefail
          # Only copy top-level .md files. Exclude specific names and any with '@' in the filename
          find external-cheatsheets -maxdepth 1 -type f -name '*.md' \
            ! -name 'CONTRIBUTING.md' \
            ! -name 'README.md' \
            ! -name 'index.md' \
            ! -name 'index@2016.md' \
            ! -name '*@*.md' \
            -print0 | xargs -0 -I {} cp {} assets/cheatsheets/

      - name: Commit and push changes (if any)
        run: |
          set -e
          if [[ -n "$(git status --porcelain assets/cheatsheets)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add assets/cheatsheets
            git commit -m "chore(cheatsheets): sync from rstacruz/cheatsheets"
            git push
          else
            echo "No changes to commit."
          fi

